#!/bin/bash

DIR=/popush
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NODE_PATH=/usr/local/lib/node_modules
NODE=/usr/local/bin/node
PID_PATH=/var/run

export NODE_PATH=$NODE_PATH
 
test -x $NODE || exit 0
 
function start_app {
  echo "Starting Popush Server"
  cd "$DIR"
  NODE_ENV=production nohup "$NODE" "app.js" 1>>"log" 2>&1 &
  echo $! > "$PID_PATH/popush.pid"
}
 
function stop_app {
  echo "Stopping Popush Server"
  kill `cat $PID_PATH/popush.pid 2>/dev/null` 2>/dev/null
}
 
case $1 in
   start)
      stop_app
      start_app ;;
    stop)
      stop_app ;;
    restart)
      stop_app
      start_app
      ;;
    *)
      echo "usage: popush {start|stop}" ;;
esac
exit 0
